### ISSUE TITLE
Laggy after new update

### ISSUE THREAD

**Issue by sitiom** [RazerMoon/vcTimer#4]
One noticeable thing after commit https://github.com/RazerMoon/vcTimer/commit/dc12d59bf69553672f1f066c509f0dbb6f703053 is that it becomes laggy at most times (freezes, then suddenly speeds/catches up).

**Comment by RazerMoon** [comment]
I don't have this problem, have you tried reloading discord after the update?

Also, could you provide an example? e.g. video

**Comment by sitiom** [comment]
> I don't have this problem, have you tried reloading discord after the update?
> 
> Also, could you provide an example? e.g. video

Here it is:

![example](https://user-images.githubusercontent.com/56180050/113791287-e4c4c280-9775-11eb-8114-6a0920fc4479.gif)

This does not happen before commit https://github.com/RazerMoon/vcTimer/commit/dc12d59bf69553672f1f066c509f0dbb6f703053.

**Comment by RazerMoon** [comment]
This likely happens due to discord lagging, and/or the date calculation being more expensive. Could also be due to the counter being more accurate now, or setInterval not being accurate etc.

Need to do more experimentation on how to resolve this, maybe use the innacurate timer to prevent skips and correct the drift every ten minutes or something?

**Comment by RazerMoon** [comment]
Actually, I think the bug lies elsewhere. `new Date(this.state.delta).toISOString().substr(11, 8)` is the method I use to get the time, which just extracts the seconds and can cause errors if a full second hasn't passed. I don't know why I didn't see that, I'll round the time to the nearest second from now on 😅

**Comment by RazerMoon** [comment]
Yep, problem is fixed now.
